# Generated by Django 6.1 on 2026-08-13 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("room", models.CharField(blank=True, max_length=60)),
                ("day", models.DateField(blank=True, null=True)),
                ("start_hour", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("duration_hours", models.PositiveSmallIntegerField(default=1)),
                ("position", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("day", "start_hour", "position", "id"),
                "indexes": [
                    models.Index(
                        fields=["owner", "day", "start_hour"],
                        name="board_event_owner_i_dccc10_idx",
                    )
                ],
            },
        ),
    ]
