"""Server-side tools, alongside the spec tools.

The board's own operations reach the agent as spec tools (see `board/specs.py`),
so what belongs here is anything that is not a board operation: a summary the ORM
can answer directly, and the two halves of AG-UI shared state.
"""

from __future__ import annotations

from collections import Counter

from ag_ui.core import EventType, StateSnapshotEvent
from django_ag_ui import ToolCategory, ToolRegistry, tool
from django_pydantic_agent import AgentDeps
from pydantic_ai import RunContext, ToolReturn

from board.models import Event

registry = ToolRegistry()


@tool(registry, category=ToolCategory.INTROSPECT, summary="Week overview")
def week_overview(ctx: RunContext[AgentDeps]) -> str:
    """Summarise the acting user's week: how many events per day, and the backlog size."""
    events = Event.objects.filter(owner=ctx.deps.user)
    per_day = Counter(event.day.isoformat() for event in events if event.day is not None)
    backlog = sum(1 for event in events if event.day is None)
    if not per_day and not backlog:
        return "The board is empty."
    scheduled = ", ".join(f"{day}: {count}" for day, count in sorted(per_day.items()))
    return f"Scheduled per day: {scheduled}. Backlog: {backlog}."


# --- AG-UI shared state -------------------------------------------------------
#
# The board's *own* state -- which view, which room filter, what is selected --
# reaches the agent as `read_board` / `set_board`, generated by the element's
# `registerPageState`. Those are ordinary tool calls: they appear in the
# transcript, and the confirmation card can gate them.
#
# The week note below is the other channel, and the contrast is narrower than it
# first looks. Writing state is still a tool call, so it still renders a card and
# could still be gated. What differs is *who changes the value and how the page
# hears about it*: `set_board` asks the browser to run the page's own writer, while
# this rewrites the object on the server and the snapshot streams back, so the page
# re-renders having executed nothing. That is what suits a document the two are
# co-editing rather than an operation one of them performs.
#
# Neither half is package machinery. `ctx.deps.state` is whatever the client
# sent, and an event returned as `ToolReturn` metadata is forwarded verbatim by
# pydantic-ai's adapter. This is the whole recipe.


@tool(registry, category=ToolCategory.INTROSPECT, summary="Read the week note")
def read_week_note(ctx: RunContext[AgentDeps]) -> str:
    """Read the shared week note the user is editing."""
    note = (ctx.deps.state or {}).get("note", "")
    return f"The week note says: {note}" if note else "The week note is empty."


@tool(registry, summary="Write the week note")
def write_week_note(ctx: RunContext[AgentDeps], body: str) -> ToolReturn:
    """Replace the shared week note with `body`."""
    ctx.deps.state = {**(ctx.deps.state or {}), "note": body}
    return ToolReturn(
        # What the model sees, and what the client sees, are different things:
        # `return_value` goes into the transcript, `metadata` onto the wire.
        return_value="Week note updated.",
        metadata=[StateSnapshotEvent(type=EventType.STATE_SNAPSHOT, snapshot=ctx.deps.state)],
    )
